# VIDEO / CAMERA

CAMERA_SOURCE          = 0
FRAME_WIDTH            = 640
FRAME_HEIGHT           = 480
TARGET_FPS             = 30
PROCESS_EVERY_N_FRAMES = 3

# YOLO SETTINGS

YOLO_MODEL_PATH    = "yolov8n.pt"
YOLO_CONFIDENCE    = 0.4
YOLO_IOU_THRESHOLD = 0.45

VEHICLE_CLASSES = ['car']
VEHICLE_CLASS_IDS = [2] #only car
